language: python

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -q
  - sudo apt-get install gcc-4.9 -y

addons:
  apt:
    sources:
    - kubuntu-backports
    - ubuntu-toolchain-r-test
    packages:
    - ninja-build
    
script:
  - cpp --version
  - gcc -v
  - g++ -v
  - echo "int main() { return 0; }" > "test.c"; gcc -c -x c -g -Wall -Wextra test.c
  - src/test/runalltests.sh
