language: python

addons:
  apt:
    sources:
    - kubuntu-backports
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.9
    - g++-4.9
    - ninja-build
    
script:
  - cpp --version
  - gcc -v
  - g++ -v
  - echo "int main() { return 0; }" | gcc -c -x c --Wall -Wextra -
  - src/test/runalltests.sh
